---
- name: Merge Sensu configs
  sensu_merge:
    suffix: _sensu_{{ item }}
    var_name: sensu_{{ item }}_merged
  with_items:
    - checks
    - handlers
    - filters
    - mutators

- name: Compile client attributes
  sensu_merge:
    suffix: _sensu_client_attributes
    var_name: sensu_client_attributes_merged

- name: Collect client subscriptions
  sensu_merge:
    suffix: _sensu_client_subscriptions
    var_name: sensu_client_subscriptions_merged
    type: list

- name: Collect extra Sensu configs
  sensu_merge:
    suffix: _sensu_extra_configs
    var_name: sensu_extra_configs_merged

# All in one file so we can validate the full config before restarts.
- name: Configure Sensu
  copy:
    dest: "{{ sensu_config_file }}"
    content: "{{ sensu_config | combine(sensu_extra_configs_merged) | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
    validate: "{{ sensu_bin }}/sensu-server -c '%s' --validate_config"
  notify:
    - restart sensu-server
    - restart sensu-api
    - restart sensu-client
