---
- name: Merge Sensu configs
  sensu_merge:
    suffix: _sensu_{{ item }}
    var_name: sensu_{{ item }}
  with_items:
  - checks
  - handlers
  - filters
  - mutators

- name: Configure Sensu
  copy:
    dest: "{{ sensu_config_file }}"
    content: "{{ sensu_config | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify:
    - restart sensu-server
    - restart sensu-api
    - restart sensu-client

- name: Configure Sensu API
  copy:
    dest: "{{ sensu_config_dir }}/api.json"
    content: "{{ {'api': sensu_api_config} | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify: restart sensu-api

- name: Configure Sensu client
  copy:
    dest: "{{ sensu_config_dir }}/client.json"
    content: "{{ {'client': sensu_client_config} | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify: restart sensu-client

- name: Configure Sensu checks
  copy:
    dest: "{{ sensu_config_dir }}/checks.json"
    content: "{{ {'checks': sensu_checks} | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify:
    - restart sensu-server
    - restart sensu-client

- name: Configure Sensu handlers
  copy:
    dest: "{{ sensu_config_dir }}/handlers.json"
    content: "{{ {'handlers': sensu_handlers} | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify: restart sensu-server

- name: Configure Sensu filters
  copy:
    dest: "{{ sensu_config_dir }}/filters.json"
    content: "{{ {'filters': sensu_filters} | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify: restart sensu-server

- name: Configure Sensu mutators
  copy:
    dest: "{{ sensu_config_dir }}/mutators.json"
    content: "{{ {'mutators': sensu_mutators} | to_nice_json }}\n"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0600
  notify: restart sensu-server
