---
- name: Make sure apt can do https
  apt:
    name: apt-transport-https
    state: present
  when:
    - sensu_install_repo
    - ansible_os_family == 'Debian'

- name: Make sure YUM can lock versions
  yum:
    name: yum-plugin-versionlock
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - sensu_install_yum_versionlock

- name: Install Sensu repo key
  apt_key:
    url: "{{ sensu_debian_repo_key_url }}"
    state: "{{ 'present' if sensu_install_repo else 'absent' }}"
  when: ansible_os_family == 'Debian'

- name: Install Sensu apt repository
  apt_repository:
    repo: "{{ sensu_debian_repo_url }}"
    filename: sensu
    state: "{{ 'present' if sensu_install_repo else 'absent' }}"
  when: ansible_os_family == 'Debian'

- name: Install yum repository
  yum_repository:
    name: sensu
    description: Sensu
    file: sensu
    baseurl: "{{ sensu_redhat_repo_url }}"
    gpgcheck: no
    enabled: yes
    state: "{{ 'present' if sensu_install_repo else 'absent' }}"
  when: ansible_os_family == 'RedHat'

- name: Pin Sensu package version
  copy:
    dest: /etc/apt/preferences.d/sensu
    content: |
      Package: sensu
      Pin: version {{ sensu_version }}
      Pin-Priority: 1002
  when:
    - ansible_os_family == 'Debian'
    - sensu_state != 'absent'
    - sensu_version|length > 0
    - sensu_pin_version

- name: Un-pin Sensu package
  file:
    path: /etc/apt/preferences.d/sensu
    state: absent
  when:
    - ansible_os_family == 'Debian'
    - sensu_state == 'absent' or sensu_version|length == 0

- name: Ensure Sensu is {{ 'UN' if not sensu_state else '' }}installed (APT)
  apt:
    name: sensu{{ ('=' + sensu_version + '*') if sensu_version|length else '' }}
    state: "{{ sensu_state }}"
  when: ansible_os_family == 'Debian'
  notify:
    - sensu daemon-reload
    - restart sensu-server
    - restart sensu-api
    - restart sensu-client

- name: Unlock sensu version in YUM
  command: yum versionlock delete sensu
  args:
    warn: no
  changed_when: false
  ignore_errors: yes
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure Sensu is {{ 'UN' if not sensu_state else '' }}installed (YUM)
  yum:
    name: sensu{{ ('-' + sensu_version + '*') if sensu_version|length else '' }}
    state: "{{ sensu_state }}"
  when: ansible_os_family == 'RedHat'
  notify:
    - sensu daemon-reload
    - restart sensu-server
    - restart sensu-api
    - restart sensu-client

- name: Lock sensu version in YUM
  command: yum versionlock sensu
  args:
    warn: no
  changed_when: false
  when:
    - ansible_os_family == 'RedHat'
    - sensu_version|length > 0
    - sensu_pin_version

- name: Make {{ sensu_base_dir }} writable by {{ sensu_group }} group
  file:
    path: "{{ sensu_base_dir }}"
    group: "{{ sensu_group }}"
    state: directory
    mode: g+rwx
