---
- name: Gather list of plugin dependencies
  sensu_merge:
    suffix: _sensu_plugin_dependencies
    var_name: sensu_plugin_dependencies_merged
    type: list

- name: Install plugin dependencies (APT)
  apt:
    name: "{{ sensu_plugin_dependencies_merged }}"
    state: present
  when: ansible_os_family == 'Debian' and sensu_plugin_dependencies_merged | length > 0

- name: Install plugin dependencies (YUM)
  yum:
    name: "{{ sensu_plugin_dependencies_merged }}"
    state: present
  when: ansible_os_family == 'RedHat' and sensu_plugin_dependencies_merged | length > 0

- name: Gather list of plugins to install
  sensu_merge:
    suffix: _sensu_plugins
    var_name: sensu_plugins_merged
    type: list

- name: Install Sensu plugins
  gem:
    name: "sensu-plugins-{{ item if item is string else item.name }}"
    state: "{{ 'present' if item is string else item.state|d('present') }}"
    version: "{{ omit if item is string else item.version|d(omit) }}"
    executable: "{{ sensu_ruby_dir }}/bin/gem"
    user_install: no
  loop: "{{ sensu_plugins_merged }}"
  loop_control:
    label: "{{ item if item is string else item.name }}{{ '' if item is string else ('-' + item.version|d('*')) }}"
  register: _sensu_install
  notify:
    - restart sensu-client
    - restart sensu-server
    - restart sensu-api
