---
- name: Install YUM repository
  yum_repository:
    name: sensu
    description: Sensu
    file: sensu
    baseurl: "{{ sensu_redhat_repo_url }}"
    gpgcheck: no
    enabled: yes
    state: "{{ 'present' if sensu_install_repo else 'absent' }}"
