---

- name: Make sure apt can do https
  apt:
    name: apt-transport-https
    state: present
  when: sensu_install_repo

- name: Install Sensu repo key
  apt_key:
    url: "{{ sensu_debian_repo_key_url }}"
    state: "{{ 'present' if sensu_install_repo else 'absent' }}"

- name: Install Sensu apt repository
  apt_repository:
    repo: "{{ sensu_debian_repo_url }}"
    filename: sensu
    state: "{{ 'present' if sensu_install_repo else 'absent' }}"
