---
# handlers file for sensu

# Use shell instead of service so we can stagger restarts in a cluster.

- name: restart sensu-server
  shell: >
    sleep {{ sensu_cluster_interval * sensu_cluster_offset }};
    systemctl restart sensu-server
  when: sensu_enable_server

- name: restart sensu-api
  shell: >
    sleep {{ sensu_cluster_interval * sensu_cluster_offset }};
    systemctl restart sensu-api
  when: sensu_enable_api

- name: restart sensu-client
  service:
    name: sensu-client
    state: restarted
  when: sensu_enable_client
