---
# handlers file for sensu

- name: restart sensu-server
  service:
    name: sensu-server
    state: restarted
  when: sensu_enable_server

- name: restart sensu-api
  service:
    name: sensu-api
    state: restarted
  when: sensu_enable_api

- name: restart sensu-client
  service:
    name: sensu-client
    state: restarted
  when: sensu_enable_client
